//= require lib/namespacing

//= require new_src/three

//= require_tree ./new_src/core
// require original_src/core/Clock
// require original_src/core/Color
// require original_src/core/Vector2
// require original_src/core/Vector3
// require original_src/core/Vector4
// require original_src/core/Matrix3
// require original_src/core/Matrix4
// require original_src/core/Math
// require original_src/core/Face3
// require original_src/core/Face4
// require original_src/core/Frustum
// require original_src/core/Projector
// require original_src/core/Ray
// require original_src/core/Spline
// require original_src/core/Geometry
// require original_src/core/Object3D
// require original_src/core/Quaternion
// require original_src/core/Rectangle
// require original_src/core/UV
// require original_src/core/Vertex

//= require_tree ./new_src/cameras
// require original_src/cameras/Camera
// require original_src/cameras/OrthographicCamera
// require original_src/cameras/PerspectiveCamera

//= require_tree ./new_src/lights
// require original_src/lights/Light
// require original_src/lights/AmbientLight
// require original_src/lights/DirectionalLight
// require original_src/lights/PointLight
// require original_src/lights/SpotLight

//= require_tree ./new_src/loaders
// require original_src/loaders/Loader
// require original_src/loaders/BinaryLoader
// require original_src/loaders/ImageLoader
// require original_src/loaders/SceneLoade
// require original_src/loaders/VTKLoader
// require original_src/loaders/ColladaLoader
// require original_src/loaders/JSONLoader
// require original_src/loaders/OBJLoader
// require original_src/loaders/UTF8Loader

//= require original_src/materials/Material
//= require original_src/materials/LineBasicMaterial
//= require original_src/materials/MeshBasicMaterial
//= require original_src/materials/MeshLambertMaterial
//= require original_src/materials/MeshPhongMaterial
//= require original_src/materials/MeshDepthMaterial
//= require original_src/materials/MeshNormalMaterial
//= require original_src/materials/MeshFaceMaterial
//= require original_src/materials/ParticleBasicMaterial
//= require original_src/materials/ParticleCanvasMaterial
//= require original_src/materials/ParticleDOMMaterial
//= require original_src/materials/ShaderMaterial
//= require original_src/textures/Texture
//= require original_src/textures/DataTexture
//= require original_src/objects/Particle
//= require original_src/objects/ParticleSystem
//= require original_src/objects/Line
//= require original_src/objects/Mesh
//= require original_src/objects/Bone
//= require original_src/objects/SkinnedMesh
//= require original_src/objects/MorphAnimMesh
//= require original_src/objects/Ribbon
//= require original_src/objects/LOD
//= require original_src/objects/Sprite
//= require original_src/scenes/Scene
//= require original_src/scenes/Fog
//= require original_src/scenes/FogExp2
//= require original_src/renderers/DOMRenderer
//= require original_src/renderers/CanvasRenderer
//= require original_src/renderers/SVGRenderer
//= require original_src/renderers/WebGLShaders
//= require original_src/renderers/WebGLRenderer
//= require original_src/renderers/WebGLRenderTarget
//= require original_src/renderers/WebGLRenderTargetCube
//= require original_src/renderers/renderables/RenderableVertex
//= require original_src/renderers/renderables/RenderableFace3
//= require original_src/renderers/renderables/RenderableFace4
//= require original_src/renderers/renderables/RenderableObject
//= require original_src/renderers/renderables/RenderableParticle
//= require original_src/renderers/renderables/RenderableLine

// extra files:
//= require original_src/extras/ColorUtils
//= require original_src/extras/GeometryUtils
//= require original_src/extras/ImageUtils
//= require original_src/extras/SceneUtils
//= require original_src/extras/ShaderUtils
//= require original_src/extras/core/BufferGeometry
//= require original_src/extras/core/Curve
//= require original_src/extras/core/CurvePath
//= require original_src/extras/core/EventTarget
//= require original_src/extras/core/Gyroscope
//= require original_src/extras/core/Path
//= require original_src/extras/core/Shape
//= require original_src/extras/core/TextPath
//= require original_src/extras/animation/AnimationHandler
//= require original_src/extras/animation/Animation
//= require original_src/extras/animation/KeyFrameAnimation
//= require original_src/extras/cameras/CubeCamera
//= require original_src/extras/cameras/CombinedCamera
//= require original_src/extras/controls/FirstPersonControls
//= require original_src/extras/controls/PathControls
//= require original_src/extras/controls/FlyControls
//= require original_src/extras/controls/RollControls
//= require original_src/extras/controls/TrackballControls
//= require original_src/extras/geometries/CubeGeometry
//= require original_src/extras/geometries/CylinderGeometry
//= require original_src/extras/geometries/ExtrudeGeometry
//= require original_src/extras/geometries/LatheGeometry
//= require original_src/extras/geometries/PlaneGeometry
//= require original_src/extras/geometries/SphereGeometry
//= require original_src/extras/geometries/TextGeometry
//= require original_src/extras/geometries/TorusGeometry
//= require original_src/extras/geometries/TorusKnotGeometry
//= require original_src/extras/geometries/TubeGeometry
//= require original_src/extras/geometries/PolyhedronGeometry
//= require original_src/extras/geometries/IcosahedronGeometry
//= require original_src/extras/geometries/OctahedronGeometry
//= require original_src/extras/geometries/TetrahedronGeometry
//= require original_src/extras/geometries/ParametricGeometry
//= require original_src/extras/helpers/AxisHelper
//= require original_src/extras/helpers/ArrowHelper
//= require original_src/extras/helpers/CameraHelper
//= require original_src/extras/modifiers/SubdivisionModifier
//= require original_src/extras/objects/ImmediateRenderObject
//= require original_src/extras/objects/LensFlare
//= require original_src/extras/objects/MorphBlendMesh
//= require original_src/extras/renderers/plugins/LensFlarePlugin
//= require original_src/extras/renderers/plugins/ShadowMapPlugin
//= require original_src/extras/renderers/plugins/SpritePlugin
//= require original_src/extras/renderers/plugins/DepthPassPlugin
//= require original_src/extras/shaders/ShaderFlares
//= require original_src/extras/shaders/ShaderSprite

